/* Generated By:JavaCC: Do not edit this line. DotParserConstants.java */
package br.jabuti.gvf;

public interface DotParserConstants {

  int EOF = 0;
  int GRAPH = 6;
  int NODE = 7;
  int TO = 8;
  int DIGRAPH = 9;
  int POS = 10;
  int BBOX = 11;
  int LPAREN = 12;
  int RPAREN = 13;
  int LBRACE = 14;
  int RBRACE = 15;
  int LBRACKET = 16;
  int RBRACKET = 17;
  int SEMICOLON = 18;
  int COMMA = 19;
  int DOT = 20;
  int EQUALS = 21;
  int GT = 22;
  int LT = 23;
  int HOOK = 24;
  int COLON = 25;
  int EQ = 26;
  int LE = 27;
  int GE = 28;
  int NE = 29;
  int PLUS = 30;
  int MINUS = 31;
  int STAR = 32;
  int SLASH = 33;
  int REM = 34;
  int POWER = 35;
  int FIXED_POINT_LITERAL = 36;
  int INTEGER_LITERAL = 37;
  int STRING_LITERAL = 38;
  int IDENTIFIER = 39;
  int LETTER = 40;
  int DIGIT = 41;
  int PARAM = 42;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"graph\"",
    "\"node\"",
    "\"->\"",
    "\"digraph\"",
    "\"pos\"",
    "\"bb\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"=\"",
    "\">\"",
    "\"<\"",
    "\"?\"",
    "\":\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"**\"",
    "<FIXED_POINT_LITERAL>",
    "<INTEGER_LITERAL>",
    "<STRING_LITERAL>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "<PARAM>",
  };

}
