/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JFrm_RequiredElements.java
 *
 * Created on Jan 26, 2009, 2:57:51 PM
 */

package jabuti.ws.gui;

import java.util.Enumeration;

import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author mareler
 */
public class JFrm_RequiredElements extends javax.swing.JFrame {

    private DefaultTableModel dataModel;

    /** Creates new form JFrm_RequiredElements */
    public JFrm_RequiredElements(int rowCount,int colCount,String required[][]) {
        initComponents();        
        this.setTitle("Required elements");
        dataModel = new DefaultTableModel();
        dataModel.setRowCount(rowCount);
        dataModel.setColumnCount(colCount);
        dataModel.setColumnIdentifiers(new String[]{"Method","All-nodes-ei","All-nodes-ed","All-edges-ei","All-edges-ed","All-uses-ei","All-uses_ed","All-pot-uses-ei","All-pot-uses-ed"});
        
        System.out.println("Row count: " + rowCount);
        
        for (int i=0; i<rowCount; i++)
        {
        	for (int j=0; j<9; j++)
        		dataModel.setValueAt(required[i][j], i, j);
        }
        /*
        System.out.println("");
			System.out.println("GetAllRequiredElements operation");
			GetAllRequiredElements in2 = new GetAllRequiredElements();
			in2.setProjectId(projectid);
			in2.setIdUserName("user");
			GetAllRequiredElementsResponse out2 = stub.getAllRequiredElements(in2);
			RequiredElementsDetails details[] = out2.get_return();
			for (int i = 0; i < details.length; i++) {
				System.out.println("--method: " + details[i].getMethodName());
				Criterion c[] = details[i].getCriterion();
				for (int j = 0; j < c.length; j++) {
					System.out.println("----Criterion: " + c[j].getName());
					System.out.print("----Elements: ");
					String elems[] = c[j].getElements();
					if(elems != null)
						for (int j2 = 0; j2 < elems.length; j2++) {
							System.out.print(elems[j2] + ", ");
						}
					System.out.println();
				}
			}			*/


        jt_result.setModel(dataModel);
        Enumeration<TableColumn> en = jt_result.getColumnModel().getColumns();
        while (en.hasMoreElements())
        	en.nextElement().setPreferredWidth(300);
        jt_result.setRowHeight(40);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jt_result = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jt_result.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Method", "All nodes ei", "All nodes ed", "All edges ei", "All edges ed", "All uses ei", "All uses ed", "All pot-uses ei", "All pot-uses ed"
            }
        ));
        jScrollPane1.setViewportView(jt_result);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1043, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {

    }

    // Variables declaration - do not modify
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jt_result;
    // End of variables declaration

}
