/* Generated By:JavaCC: Do not edit this line. PascalConstants.java */
public interface PascalConstants {

  int EOF = 0;
  int AND = 1;
  int ARRAY = 2;
  int BEGIN = 3;
  int CASE = 4;
  int CHAR = 5;
  int CONST = 6;
  int DIV = 7;
  int DO = 8;
  int DOWNTO = 9;
  int ELSE = 10;
  int END = 11;
  int FOR = 12;
  int FUNCTION = 13;
  int GOTO = 14;
  int IF = 15;
  int IN = 16;
  int LABEL = 17;
  int MOD = 18;
  int NOT = 19;
  int OF = 20;
  int OR = 21;
  int PACKED = 22;
  int PROCEDURE = 23;
  int PROGRAM = 24;
  int RECORD = 25;
  int REPEAT = 26;
  int SET = 27;
  int THEN = 28;
  int TO = 29;
  int TYPE = 30;
  int UNTIL = 31;
  int VAR = 32;
  int WHILE = 33;
  int WITH = 34;
  int MAIS = 35;
  int MENOS = 36;
  int ASTERISCO = 37;
  int BARRA = 38;
  int IGUAL = 39;
  int MENOR = 40;
  int MAIOR = 41;
  int ABRE_COLCHETE = 42;
  int FECHA_COLCHETE = 43;
  int PONTO = 44;
  int VIRGULA = 45;
  int DOIS_PONTOS = 46;
  int PONTO_VIRGULA = 47;
  int ABRE_PARENTESE = 48;
  int FECHA_PARENTESE = 49;
  int DIFERENTE = 50;
  int MENOR_IGUAL = 51;
  int MAIOR_IGUAL = 52;
  int ATRIBUICAO = 53;
  int PONTO_PONTO = 54;
  int APOSTROFE = 55;
  int IDENTIFICADOR = 56;
  int NUMERO = 57;
  int INTEIRO_LITERAL = 58;
  int FLOATING_POINT_LITERAL = 59;
  int EXPOENTE = 60;
  int LETRA = 61;
  int DIGITO = 62;
  int ROTULO = 63;
  int CARACTER = 64;
  int INTERVALO = 65;
  int COMENTARIO = 66;
  int INICIO_COMENTARIO_CHAVE = 67;
  int INICIO_COMENTARIO_PARENTESE_ASTERISCO = 68;
  int FIM_COMENTARIO_CHAVE = 69;
  int FIM_COMENTARIO_PARENTESE_ASTERISCO = 70;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\"and\"",
    "\"array\"",
    "\"begin\"",
    "\"case\"",
    "\"char\"",
    "\"const\"",
    "\"div\"",
    "\"do\"",
    "\"downto\"",
    "\"else\"",
    "\"end\"",
    "\"for\"",
    "\"function\"",
    "\"goto\"",
    "\"if\"",
    "\"in\"",
    "\"label\"",
    "\"mod\"",
    "\"not\"",
    "\"of\"",
    "\"or\"",
    "\"packed\"",
    "\"procedure\"",
    "\"program\"",
    "\"record\"",
    "\"repeat\"",
    "\"set\"",
    "\"then\"",
    "\"to\"",
    "\"type\"",
    "\"until\"",
    "\"var\"",
    "\"while\"",
    "\"with\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"=\"",
    "\"<\"",
    "\">\"",
    "\"[\"",
    "\"]\"",
    "\".\"",
    "\",\"",
    "\":\"",
    "\";\"",
    "\"(\"",
    "\")\"",
    "\"<>\"",
    "\"<=\"",
    "\">=\"",
    "\":=\"",
    "\"..\"",
    "\"\\\'\"",
    "<IDENTIFICADOR>",
    "<NUMERO>",
    "<INTEIRO_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<EXPOENTE>",
    "<LETRA>",
    "<DIGITO>",
    "<ROTULO>",
    "<CARACTER>",
    "<INTERVALO>",
    "<COMENTARIO>",
    "\"{\"",
    "\"(*\"",
    "\"}\"",
    "\"*)\"",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"\"",
  };

}
