package it.eng.spago4q.metadata;

// Generated 27-ago-2009 10.54.02 by Hibernate Tools 3.2.2.GA

/**
 * QpsProjectDetail generated by hbm2java
 */
public class QpsProjectDetail implements java.io.Serializable {

	private static final long serialVersionUID = 5351814062590954291L;
	private Integer prjDetailId;
	private String code;
	private String detail;

	public QpsProjectDetail() {
	}

	public QpsProjectDetail(String code) {
		this.code = code;
	}
	
	public QpsProjectDetail(Integer id, String code, String detail) {
		this.prjDetailId = id;
		this.code = code;
		this.detail = detail;
	}

	public QpsProjectDetail(String code, String detail) {
		this.code = code;
		this.detail = detail;
	}

	public Integer getPrjDetailId() {
		return this.prjDetailId;
	}

	public void setPrjDetailId(Integer prjDetailId) {
		this.prjDetailId = prjDetailId;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getDetail() {
		return this.detail;
	}

	public void setDetail(String detail) {
		this.detail = detail;
	}

}
